package com.example.utils

data class SupportedLanguage(
    val code: String,
    val name: String,
    val nativeName: String,
    val flag: String
)

object LanguageList {
    val languages: List<SupportedLanguage> = listOf(
        SupportedLanguage("ur", "Urdu", "اردو", "🇵🇰"),
        SupportedLanguage("en", "English", "English", "🇬🇧"),
        SupportedLanguage("ar", "Arabic", "العربية", "🇸🇦"),
        SupportedLanguage("fa", "Persian / Farsi", "فارسی", "🇮🇷"),
        SupportedLanguage("ps", "Pashto", "پښتو", "🇦🇫"),
        SupportedLanguage("pa", "Punjabi", "ਪੰਜਾਬੀ / پنجابی", "🇵🇰"),
        SupportedLanguage("sd", "Sindhi", "سنڌي", "🇵🇰"),
        SupportedLanguage("bal", "Balochi", "بلوچی", "🇵🇰"),
        SupportedLanguage("skr", "Saraiki", "سرائیکی", "🇵🇰"),
        SupportedLanguage("ks", "Kashmiri", "کٲشُر", "🇵🇰"),
        SupportedLanguage("hi", "Hindi", "हिन्दी", "🇮🇳"),
        SupportedLanguage("bn", "Bengali", "বাংলা", "🇧🇩"),
        SupportedLanguage("es", "Spanish", "Español", "🇪🇸"),
        SupportedLanguage("fr", "French", "Français", "🇫🇷"),
        SupportedLanguage("de", "German", "Deutsch", "🇩🇪"),
        SupportedLanguage("it", "Italian", "Italiano", "🇮🇹"),
        SupportedLanguage("pt", "Portuguese", "Português", "🇵🇹"),
        SupportedLanguage("ru", "Russian", "Русский", "🇷🇺"),
        SupportedLanguage("zh", "Chinese (Simplified)", "简体中文", "🇨🇳"),
        SupportedLanguage("zh-TW", "Chinese (Traditional)", "繁體中文", "🇹🇼"),
        SupportedLanguage("ja", "Japanese", "日本語", "🇯🇵"),
        SupportedLanguage("ko", "Korean", "한국어", "🇰🇷"),
        SupportedLanguage("tr", "Turkish", "Türkçe", "🇹🇷"),
        SupportedLanguage("id", "Indonesian", "Bahasa Indonesia", "🇮🇩"),
        SupportedLanguage("ms", "Malay", "Bahasa Melayu", "🇲🇾"),
        SupportedLanguage("tl", "Tagalog / Filipino", "Filipino", "🇵🇭"),
        SupportedLanguage("vi", "Vietnamese", "Tiếng Việt", "🇻🇳"),
        SupportedLanguage("th", "Thai", "ไทย", "🇹🇭"),
        SupportedLanguage("nl", "Dutch", "Nederlands", "🇳🇱"),
        SupportedLanguage("sv", "Swedish", "Svenska", "🇸🇪"),
        SupportedLanguage("no", "Norwegian", "Norsk", "🇳🇴"),
        SupportedLanguage("da", "Danish", "Dansk", "🇩🇰"),
        SupportedLanguage("fi", "Finnish", "Suomi", "🇫🇮"),
        SupportedLanguage("pl", "Polish", "Polski", "🇵🇱"),
        SupportedLanguage("uk", "Ukrainian", "Українська", "🇺🇦"),
        SupportedLanguage("cs", "Czech", "Čeština", "🇨🇿"),
        SupportedLanguage("sk", "Slovak", "Slovenčina", "🇸🇰"),
        SupportedLanguage("hu", "Hungarian", "Magyar", "🇭🇺"),
        SupportedLanguage("ro", "Romanian", "Română", "🇷🇴"),
        SupportedLanguage("bg", "Bulgarian", "Български", "🇧🇬"),
        SupportedLanguage("el", "Greek", "Ελληνικά", "🇬🇷"),
        SupportedLanguage("he", "Hebrew", "עברית", "🇮🇱"),
        SupportedLanguage("sw", "Swahili", "Kiswahili", "🇰🇪"),
        SupportedLanguage("am", "Amharic", "አማርኛ", "🇪🇹"),
        SupportedLanguage("yo", "Yoruba", "Èdè Yorùbá", "🇳🇬"),
        SupportedLanguage("ig", "Igbo", "Asụsụ Igbo", "🇳🇬"),
        SupportedLanguage("ha", "Hausa", "Harshen Hausa", "🇳🇬"),
        SupportedLanguage("zu", "Zulu", "isiZulu", "🇿🇦"),
        SupportedLanguage("af", "Afrikaans", "Afrikaans", "🇿🇦"),
        SupportedLanguage("gu", "Gujarati", "ગુજરાતી", "🇮🇳"),
        SupportedLanguage("mr", "Marathi", "मराठी", "🇮🇳"),
        SupportedLanguage("ta", "Tamil", "தமிழ்", "🇮🇳"),
        SupportedLanguage("te", "Telugu", "తెలుగు", "🇮🇳"),
        SupportedLanguage("kn", "Kannada", "ಕನ್ನಡ", "🇮🇳"),
        SupportedLanguage("ml", "Malayalam", "മലയാളം", "🇮🇳"),
        SupportedLanguage("ne", "Nepali", "नेपाली", "🇳🇵"),
        SupportedLanguage("si", "Sinhala", "සිංහල", "🇱🇰"),
        SupportedLanguage("my", "Burmese", "မြန်မာစာ", "🇲🇲"),
        SupportedLanguage("km", "Khmer", "ភាសាខ្មែរ", "🇰🇭"),
        SupportedLanguage("lo", "Lao", "ພາສາລາວ", "🇱🇦"),
        SupportedLanguage("kk", "Kazakh", "Қазақ тілі", "🇰🇿"),
        SupportedLanguage("uz", "Uzbek", "Oʻzbekcha", "🇺🇿"),
        SupportedLanguage("az", "Azerbaijani", "Azərbaycan", "🇦🇿"),
        SupportedLanguage("ka", "Georgian", "ქართული", "🇬🇪"),
        SupportedLanguage("hy", "Armenian", "Հայերեն", "🇦🇲"),
        SupportedLanguage("mn", "Mongolian", "Монгол", "🇲🇳"),
        SupportedLanguage("so", "Somali", "Soomaaliga", "🇸🇴"),
        SupportedLanguage("ku", "Kurdish", "Kurdî", "🇮🇶"),
        SupportedLanguage("sq", "Albanian", "Shqip", "🇦🇱"),
        SupportedLanguage("sr", "Serbian", "Српски", "🇷🇸"),
        SupportedLanguage("hr", "Croatian", "Hrvatski", "🇭🇷"),
        SupportedLanguage("bs", "Bosnian", "Bosanski", "🇧🇦"),
        SupportedLanguage("sl", "Slovenian", "Slovenščina", "🇸🇮"),
        SupportedLanguage("mk", "Macedonian", "Македонски", "🇲🇰"),
        SupportedLanguage("et", "Estonian", "Eesti", "🇪🇪"),
        SupportedLanguage("lv", "Latvian", "Latviešu", "🇱🇻"),
        SupportedLanguage("lt", "Lithuanian", "Lietuvių", "🇱🇹"),
        SupportedLanguage("is", "Icelandic", "Íslenska", "🇮🇸"),
        SupportedLanguage("ga", "Irish", "Gaeilge", "🇮🇪"),
        SupportedLanguage("cy", "Welsh", "Cymraeg", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
        SupportedLanguage("gl", "Galician", "Galego", "🇪🇸"),
        SupportedLanguage("eu", "Basque", "Euskara", "🇪🇸"),
        SupportedLanguage("ca", "Catalan", "Català", "🇪🇸"),
        SupportedLanguage("mt", "Maltese", "Malti", "🇲🇹"),
        SupportedLanguage("la", "Latin", "Latina", "🏛️"),
        SupportedLanguage("eo", "Esperanto", "Esperanto", "🌍"),
        SupportedLanguage("tg", "Tajik", "Тоҷикӣ", "🇹🇯"),
        SupportedLanguage("ky", "Kyrgyz", "Кыргызча", "🇰🇬"),
        SupportedLanguage("tk", "Turkmen", "Türkmençe", "🇹🇲"),
        SupportedLanguage("be", "Belarusian", "Беларуская", "🇧🇾"),
        SupportedLanguage("ug", "Uyghur", "ئۇيغۇرچە", "🇨🇳"),
        SupportedLanguage("jv", "Javanese", "Basa Jawa", "🇮🇩"),
        SupportedLanguage("su", "Sundanese", "Basa Sunda", "🇮🇩"),
        SupportedLanguage("ceb", "Cebuano", "Sinugboanon", "🇵🇭"),
        SupportedLanguage("mg", "Malagasy", "Malagasy", "🇲🇬"),
        SupportedLanguage("ny", "Chichewa", "Chichewa", "🇲🇼"),
        SupportedLanguage("st", "Sesotho", "Sesotho", "🇱🇸"),
        SupportedLanguage("sn", "Shona", "chiShona", "🇿🇼"),
        SupportedLanguage("xh", "Xhosa", "isiXhosa", "🇿🇦"),
        SupportedLanguage("rw", "Kinyarwanda", "Ikinyarwanda", "🇷🇼"),
        SupportedLanguage("or", "Odia", "ଓଡ଼ିଆ", "🇮🇳"),
        SupportedLanguage("as", "Assamese", "অসমীয়া", "🇮🇳"),
        SupportedLanguage("bho", "Bhojpuri", "भोजपुरी", "🇮🇳")
    )
}
